#!/bin/bash
#
# update generated C files from the cw export location
cd main || exit 1;
if [ "$#" -eq 0 ]; then
	for i in *.h *.c *.inc; do [ -r /tmp/cw_export/$i ] && diff $i /tmp/cw_export/$i; done;
else
	for i in $*; do [ -r /tmp/cw_export/$i ] && diff $i /tmp/cw_export/$i; done;
fi
