#!/bin/bash
#
# update generated C files from the cw export location
cd main || exit 1
rm -f cw_*.{h,c,inc}
cp /tmp/cw_export/cw_* .
#for i in *.h *.c *.inc; do [ -r /tmp/cw_export/$i ] && cp /tmp/cw_export/$i .; done;
echo | tr -d '\n' >project.h ; for i in *.h; do [ ! $i = "project.h" ] && echo '#include "'$i'"' >> project.h; done
